#ifndef __Wpanel_box_count__
#define __Wpanel_box_count__

/**
@file
Subclass of panel_box_count, which is generated by wxFormBuilder.
*/

#include "WxBoxCount.h"

//// end generated include

/** Implementing panel_box_count */
class Wpanel_box_count : public panel_box_count
{
	protected:
		// Handlers for panel_box_count events.
		void on_button_preview_cam_( wxCommandEvent& event );
		void on_button_new_( wxCommandEvent& event );
		void on_button_start_( wxCommandEvent& event );
		void on_button_stop_( wxCommandEvent& event );
	public:
		/** Constructor */
		Wpanel_box_count( wxWindow* parent );
	//// end generated class members

};

#endif // __Wpanel_box_count__
